version: '3.8'

services:
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: pokedex
    volumes:
      - database_data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - database
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  database_data:
    driver: local
