db = db.getSiblingDB('pokedex');

db.createUser({
    user: 'pokedexApp',
    pwd: 'app123!',
    roles: [
        { role: 'readWrite', db: 'pokedex' }
    ]
});

db.createCollection('Pokemon');
db.createCollection('Types');

/**********************************/
/*********** SEEDING **************/
/**********************************/

const types = [
    { name: 'Normal', weaknesses: [], strengths: [], color: '#A8A878' },
    { name: 'Fire', weaknesses: ['Water', 'Rock', 'Ground'], strengths: ['Grass', 'Bug', 'Ice', 'Steel'], color: '#F08030' },
    { name: 'Water', weaknesses: ['Electric', 'Grass'], strengths: ['Fire', 'Ground', 'Rock'], color: '#6890F0' },
    { name: 'Grass', weaknesses: ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'], strengths: ['Water', 'Ground', 'Rock'], color: '#78C850' },
    { name: 'Electric', weaknesses: ['Ground'], strengths: ['Water', 'Flying'], color: '#F8D030' },
    { name: 'Ice', weaknesses: ['Fire', 'Fighting', 'Rock', 'Steel'], strengths: ['Grass', 'Ground', 'Flying', 'Dragon'], color: '#98D8D8' },
    { name: 'Fighting', weaknesses: ['Psychic', 'Flying', 'Fairy'], strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'], color: '#C03028' },
    { name: 'Poison', weaknesses: ['Ground', 'Psychic'], strengths: ['Grass', 'Fairy'], color: '#A040A0' },
    { name: 'Ground', weaknesses: ['Water', 'Grass', 'Ice'], strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'], color: '#E0C068' },
    { name: 'Flying', weaknesses: ['Electric', 'Ice', 'Rock'], strengths: ['Grass', 'Fighting', 'Bug'], color: '#A890F0' },
    { name: 'Psychic', weaknesses: ['Bug', 'Ghost', 'Dark'], strengths: ['Fighting', 'Poison'], color: '#F85888' },
    { name: 'Bug', weaknesses: ['Fire', 'Flying', 'Rock'], strengths: ['Grass', 'Psychic', 'Dark'], color: '#A8B820' },
    { name: 'Rock', weaknesses: ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'], strengths: ['Fire', 'Ice', 'Flying', 'Bug'], color: '#B8A038' },
    { name: 'Ghost', weaknesses: ['Ghost', 'Dark'], strengths: ['Psychic', 'Ghost'], color: '#705898' },
    { name: 'Dragon', weaknesses: ['Ice', 'Dragon', 'Fairy'], strengths: ['Dragon'], color: '#7038F8' },
    { name: 'Dark', weaknesses: ['Fighting', 'Bug', 'Fairy'], strengths: ['Psychic', 'Ghost'], color: '#705848' },
    { name: 'Steel', weaknesses: ['Fire', 'Fighting', 'Ground'], strengths: ['Ice', 'Rock', 'Fairy'], color: '#B8B8D0' },
    { name: 'Fairy', weaknesses: ['Poison', 'Steel'], strengths: ['Fighting', 'Dragon', 'Dark'], color: '#F0B6BC' }
];
db.Types.insertMany(types);

const pokemons = [
    { _id: 1, name: 'Bulbasaur', types: ['Grass', 'Poison'], evolvesFromId: null, evolvesToIds: [2] },
    { _id: 2, name: 'Ivysaur', types: ['Grass', 'Poison'], evolvesFromId: 1, evolvesToIds: [3] },
    { _id: 3, name: 'Venusaur', types: ['Grass', 'Poison'], evolvesFromId: 2, evolvesToIds: [] },
    { _id: 4, name: 'Charmander', types: ['Fire'], evolvesFromId: null, evolvesToIds: [5] },
    { _id: 5, name: 'Charmeleon', types: ['Fire'], evolvesFromId: 4, evolvesToIds: [6] },
    { _id: 6, name: 'Charizard', types: ['Fire', 'Flying'], evolvesFromId: 5, evolvesToIds: [] },
    { _id: 7, name: 'Squirtle', types: ['Water'], evolvesFromId: null, evolvesToIds: [8] },
    { _id: 8, name: 'Wartortle', types: ['Water'], evolvesFromId: 7, evolvesToIds: [9] },
    { _id: 9, name: 'Blastoise', types: ['Water'], evolvesFromId: 8, evolvesToIds: [] },
    { _id: 10, name: 'Caterpie', types: ['Bug'], evolvesFromId: null, evolvesToIds: [11] },
    { _id: 11, name: 'Metapod', types: ['Bug'], evolvesFromId: 10, evolvesToIds: [12] },
    { _id: 12, name: 'Butterfree', types: ['Bug', 'Flying'], evolvesFromId: 11, evolvesToIds: [] },
    { _id: 13, name: 'Weedle', types: ['Bug', 'Poison'], evolvesFromId: null, evolvesToIds: [14] },
    { _id: 14, name: 'Kakuna', types: ['Bug', 'Poison'], evolvesFromId: 13, evolvesToIds: [15] },
    { _id: 15, name: 'Beedrill', types: ['Bug', 'Poison'], evolvesFromId: 14, evolvesToIds: [] },
    { _id: 16, name: 'Pidgey', types: ['Normal', 'Flying'], evolvesFromId: null, evolvesToIds: [17] },
    { _id: 17, name: 'Pidgeotto', types: ['Normal', 'Flying'], evolvesFromId: 16, evolvesToIds: [18] },
    { _id: 18, name: 'Pidgeot', types: ['Normal', 'Flying'], evolvesFromId: 17, evolvesToIds: [] },
    { _id: 19, name: 'Rattata', types: ['Normal'], evolvesFromId: null, evolvesToIds: [20] },
    { _id: 20, name: 'Raticate', types: ['Normal'], evolvesFromId: 19, evolvesToIds: [] },
    { _id: 21, name: 'Spearow', types: ['Normal', 'Flying'], evolvesFromId: null, evolvesToIds: [22] },
    { _id: 22, name: 'Fearow', types: ['Normal', 'Flying'], evolvesFromId: 21, evolvesToIds: [] },
    { _id: 23, name: 'Ekans', types: ['Poison'], evolvesFromId: null, evolvesToIds: [24] },
    { _id: 24, name: 'Arbok', types: ['Poison'], evolvesFromId: 23, evolvesToIds: [] },
    { _id: 25, name: 'Pikachu', types: ['Electric'], evolvesFromId: null, evolvesToIds: [26] },
    { _id: 26, name: 'Raichu', types: ['Electric'], evolvesFromId: 25, evolvesToIds: [] },
    { _id: 27, name: 'Sandshrew', types: ['Ground'], evolvesFromId: null, evolvesToIds: [28] },
    { _id: 28, name: 'Sandslash', types: ['Ground'], evolvesFromId: 27, evolvesToIds: [] },
    { _id: 29, name: 'Nidoran♀', types: ['Poison'], evolvesFromId: null, evolvesToIds: [30] },
    { _id: 30, name: 'Nidorina', types: ['Poison'], evolvesFromId: 29, evolvesToIds: [31] },
    { _id: 31, name: 'Nidoqueen', types: ['Poison', 'Ground'], evolvesFromId: 30, evolvesToIds: [] },
    { _id: 32, name: 'Nidoran♂', types: ['Poison'], evolvesFromId: null, evolvesToIds: [33] },
    { _id: 33, name: 'Nidorino', types: ['Poison'], evolvesFromId: 32, evolvesToIds: [34] },
    { _id: 34, name: 'Nidoking', types: ['Poison', 'Ground'], evolvesFromId: 33, evolvesToIds: [] },
    { _id: 35, name: 'Clefairy', types: ['Fairy'], evolvesFromId: null, evolvesToIds: [36] },
    { _id: 36, name: 'Clefable', types: ['Fairy'], evolvesFromId: 35, evolvesToIds: [] },
    { _id: 37, name: 'Vulpix', types: ['Fire'], evolvesFromId: null, evolvesToIds: [38] },
    { _id: 38, name: 'Ninetales', types: ['Fire'], evolvesFromId: 37, evolvesToIds: [] },
    { _id: 39, name: 'Jigglypuff', types: ['Normal', 'Fairy'], evolvesFromId: null, evolvesToIds: [40] },
    { _id: 40, name: 'Wigglytuff', types: ['Normal', 'Fairy'], evolvesFromId: 39, evolvesToIds: [] },
    { _id: 41, name: 'Zubat', types: ['Poison', 'Flying'], evolvesFromId: null, evolvesToIds: [42] },
    { _id: 42, name: 'Golbat', types: ['Poison', 'Flying'], evolvesFromId: 41, evolvesToIds: [] },
    { _id: 43, name: 'Oddish', types: ['Grass', 'Poison'], evolvesFromId: null, evolvesToIds: [44] },
    { _id: 44, name: 'Gloom', types: ['Grass', 'Poison'], evolvesFromId: 43, evolvesToIds: [45] },
    { _id: 45, name: 'Vileplume', types: ['Grass', 'Poison'], evolvesFromId: 44, evolvesToIds: [] },
    { _id: 46, name: 'Paras', types: ['Bug', 'Grass'], evolvesFromId: null, evolvesToIds: [47] },
    { _id: 47, name: 'Parasect', types: ['Bug', 'Grass'], evolvesFromId: 46, evolvesToIds: [] },
    { _id: 48, name: 'Venonat', types: ['Bug', 'Poison'], evolvesFromId: null, evolvesToIds: [49] },
    { _id: 49, name: 'Venomoth', types: ['Bug', 'Poison'], evolvesFromId: 48, evolvesToIds: [] },
    { _id: 50, name: 'Diglett', types: ['Ground'], evolvesFromId: null, evolvesToIds: [51] },
    { _id: 51, name: 'Dugtrio', types: ['Ground'], evolvesFromId: 50, evolvesToIds: [] },
    { _id: 52, name: 'Meowth', types: ['Normal'], evolvesFromId: null, evolvesToIds: [53] },
    { _id: 53, name: 'Persian', types: ['Normal'], evolvesFromId: 52, evolvesToIds: [] },
    { _id: 54, name: 'Psyduck', types: ['Water'], evolvesFromId: null, evolvesToIds: [55] },
    { _id: 55, name: 'Golduck', types: ['Water'], evolvesFromId: 54, evolvesToIds: [] },
    { _id: 56, name: 'Mankey', types: ['Fighting'], evolvesFromId: null, evolvesToIds: [57] },
    { _id: 57, name: 'Primeape', types: ['Fighting'], evolvesFromId: 56, evolvesToIds: [] },
    { _id: 58, name: 'Growlithe', types: ['Fire'], evolvesFromId: null, evolvesToIds: [59] },
    { _id: 59, name: 'Arcanine', types: ['Fire'], evolvesFromId: 58, evolvesToIds: [] },
    { _id: 60, name: 'Poliwag', types: ['Water'], evolvesFromId: null, evolvesToIds: [61] },
    { _id: 61, name: 'Poliwhirl', types: ['Water'], evolvesFromId: 60, evolvesToIds: [62] },
    { _id: 62, name: 'Poliwrath', types: ['Water', 'Fighting'], evolvesFromId: 61, evolvesToIds: [] },
    { _id: 63, name: 'Abra', types: ['Psychic'], evolvesFromId: null, evolvesToIds: [64] },
    { _id: 64, name: 'Kadabra', types: ['Psychic'], evolvesFromId: 63, evolvesToIds: [65] },
    { _id: 65, name: 'Alakazam', types: ['Psychic'], evolvesFromId: 64, evolvesToIds: [] },
    { _id: 66, name: 'Machop', types: ['Fighting'], evolvesFromId: null, evolvesToIds: [67] },
    { _id: 67, name: 'Machoke', types: ['Fighting'], evolvesFromId: 66, evolvesToIds: [68] },
    { _id: 68, name: 'Machamp', types: ['Fighting'], evolvesFromId: 67, evolvesToIds: [] },
    { _id: 69, name: 'Bellsprout', types: ['Grass', 'Poison'], evolvesFromId: null, evolvesToIds: [70] },
    { _id: 70, name: 'Weepinbell', types: ['Grass', 'Poison'], evolvesFromId: 69, evolvesToIds: [71] },
    { _id: 71, name: 'Victreebel', types: ['Grass', 'Poison'], evolvesFromId: 70, evolvesToIds: [] },
    { _id: 72, name: 'Tentacool', types: ['Water', 'Poison'], evolvesFromId: null, evolvesToIds: [73] },
    { _id: 73, name: 'Tentacruel', types: ['Water', 'Poison'], evolvesFromId: 72, evolvesToIds: [] },
    { _id: 74, name: 'Geodude', types: ['Rock', 'Ground'], evolvesFromId: null, evolvesToIds: [75] },
    { _id: 75, name: 'Graveler', types: ['Rock', 'Ground'], evolvesFromId: 74, evolvesToIds: [76] },
    { _id: 76, name: 'Golem', types: ['Rock', 'Ground'], evolvesFromId: 75, evolvesToIds: [] },
    { _id: 77, name: 'Ponyta', types: ['Fire'], evolvesFromId: null, evolvesToIds: [78] },
    { _id: 78, name: 'Rapidash', types: ['Fire'], evolvesFromId: 77, evolvesToIds: [] },
    { _id: 79, name: 'Slowpoke', types: ['Water', 'Psychic'], evolvesFromId: null, evolvesToIds: [80] },
    { _id: 80, name: "Slowbro", types: ["Water", "Psychic"], evolvesFromId: 79, evolvesToIds: [81] },
    { _id: 81, name: "Magnemite", types: ["Electric", "Steel"], evolvesFromId: null, evolvesToIds: [82] },
    { _id: 82, name: "Magneton", types: ["Electric", "Steel"], evolvesFromId: 81, evolvesToIds: null },
    { _id: 83, name: "Farfetch’d", types: ["Normal", "Flying"], evolvesFromId: null, evolvesToIds: null },
    { _id: 84, name: "Doduo", types: ["Normal", "Flying"], evolvesFromId: null, evolvesToIds: [85] },
    { _id: 85, name: "Dodrio", types: ["Normal", "Flying"], evolvesFromId: 84, evolvesToIds: null },
    { _id: 86, name: "Seel", types: ["Water"], evolvesFromId: null, evolvesToIds: [87] },
    { _id: 87, name: "Dewgong", types: ["Water", "Ice"], evolvesFromId: 86, evolvesToIds: null },
    { _id: 88, name: "Grimer", types: ["Poison"], evolvesFromId: null, evolvesToIds: [89] },
    { _id: 89, name: "Muk", types: ["Poison"], evolvesFromId: 88, evolvesToIds: null },
    { _id: 90, name: "Shellder", types: ["Water"], evolvesFromId: null, evolvesToIds: [91] },
    { _id: 91, name: "Cloyster", types: ["Water", "Ice"], evolvesFromId: 90, evolvesToIds: null },
    { _id: 92, name: "Gastly", types: ["Ghost", "Poison"], evolvesFromId: null, evolvesToIds: [93] },
    { _id: 93, name: "Haunter", types: ["Ghost", "Poison"], evolvesFromId: 92, evolvesToIds: [94] },
    { _id: 94, name: "Gengar", types: ["Ghost", "Poison"], evolvesFromId: 93, evolvesToIds: null },
    { _id: 95, name: "Onix", types: ["Rock", "Ground"], evolvesFromId: null, evolvesToIds: [112] },
    { _id: 96, name: "Drowzee", types: ["Psychic"], evolvesFromId: null, evolvesToIds: [97] },
    { _id: 97, name: "Hypno", types: ["Psychic"], evolvesFromId: 96, evolvesToIds: null },
    { _id: 98, name: "Krabby", types: ["Water"], evolvesFromId: null, evolvesToIds: [99] },
    { _id: 99, name: "Kingler", types: ["Water"], evolvesFromId: 98, evolvesToIds: null },
    { _id: 100, name: "Voltorb", types: ["Electric"], evolvesFromId: null, evolvesToIds: [101] },
    { _id: 101, name: "Electrode", types: ["Electric"], evolvesFromId: 100, evolvesToIds: null },
    { _id: 102, name: "Exeggcute", types: ["Grass", "Psychic"], evolvesFromId: null, evolvesToIds: [103] },
    { _id: 103, name: "Exeggutor", types: ["Grass", "Psychic"], evolvesFromId: 102, evolvesToIds: null },
    { _id: 104, name: "Cubone", types: ["Ground"], evolvesFromId: null, evolvesToIds: [105] },
    { _id: 105, name: "Marowak", types: ["Ground"], evolvesFromId: 104, evolvesToIds: null },
    { _id: 106, name: "Hitmonlee", types: ["Fighting"], evolvesFromId: null, evolvesToIds: null },
    { _id: 107, name: "Hitmonchan", types: ["Fighting"], evolvesFromId: null, evolvesToIds: null },
    { _id: 108, name: "Lickitung", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 109, name: "Koffing", types: ["Poison"], evolvesFromId: null, evolvesToIds: [110] },
    { _id: 110, name: "Weezing", types: ["Poison"], evolvesFromId: 109, evolvesToIds: null },
    { _id: 111, name: "Rhyhorn", types: ["Ground", "Rock"], evolvesFromId: null, evolvesToIds: [112] },
    { _id: 112, name: "Rhydon", types: ["Ground", "Rock"], evolvesFromId: 111, evolvesToIds: null },
    { _id: 113, name: "Chansey", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 114, name: "Tangela", types: ["Grass"], evolvesFromId: null, evolvesToIds: null },
    { _id: 115, name: "Kangaskhan", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 116, name: "Horsea", types: ["Water"], evolvesFromId: null, evolvesToIds: [117] },
    { _id: 117, name: "Seadra", types: ["Water"], evolvesFromId: 116, evolvesToIds: null },
    { _id: 118, name: "Goldeen", types: ["Water"], evolvesFromId: null, evolvesToIds: [119] },
    { _id: 119, name: "Seaking", types: ["Water"], evolvesFromId: 118, evolvesToIds: null },
    { _id: 120, name: "Staryu", types: ["Water"], evolvesFromId: null, evolvesToIds: [121] },
    { _id: 121, name: "Starmie", types: ["Water", "Psychic"], evolvesFromId: 120, evolvesToIds: null },
    { _id: 122, name: "Mr. Mime", types: ["Psychic", "Fairy"], evolvesFromId: null, evolvesToIds: null },
    { _id: 123, name: "Scyther", types: ["Bug", "Flying"], evolvesFromId: null, evolvesToIds: null },
    { _id: 124, name: "Jynx", types: ["Ice", "Psychic"], evolvesFromId: null, evolvesToIds: null },
    { _id: 125, name: "Electabuzz", types: ["Electric"], evolvesFromId: null, evolvesToIds: null },
    { _id: 126, name: "Magmar", types: ["Fire"], evolvesFromId: null, evolvesToIds: null },
    { _id: 127, name: "Pinsir", types: ["Bug"], evolvesFromId: null, evolvesToIds: null },
    { _id: 128, name: "Tauros", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 129, name: "Magikarp", types: ["Water"], evolvesFromId: null, evolvesToIds: [130] },
    { _id: 130, name: "Gyarados", types: ["Water", "Flying"], evolvesFromId: 129, evolvesToIds: null },
    { _id: 131, name: "Lapras", types: ["Water", "Ice"], evolvesFromId: null, evolvesToIds: null },
    { _id: 132, name: "Ditto", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 133, name: "Eevee", types: ["Normal"], evolvesFromId: null, evolvesToIds: [134, 135, 136] },
    { _id: 134, name: "Vaporeon", types: ["Water"], evolvesFromId: 133, evolvesToIds: null },
    { _id: 135, name: "Jolteon", types: ["Electric"], evolvesFromId: 133, evolvesToIds: null },
    { _id: 136, name: "Flareon", types: ["Fire"], evolvesFromId: 133, evolvesToIds: null },
    { _id: 137, name: "Porygon", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 138, name: "Omanyte", types: ["Rock", "Water"], evolvesFromId: null, evolvesToIds: [139] },
    { _id: 139, name: "Omastar", types: ["Rock", "Water"], evolvesFromId: 138, evolvesToIds: null },
    { _id: 140, name: "Kabuto", types: ["Rock", "Water"], evolvesFromId: null, evolvesToIds: [141] },
    { _id: 141, name: "Kabutops", types: ["Rock", "Water"], evolvesFromId: 140, evolvesToIds: null },
    { _id: 142, name: "Aerodactyl", types: ["Rock", "Flying"], evolvesFromId: null, evolvesToIds: null },
    { _id: 143, name: "Snorlax", types: ["Normal"], evolvesFromId: null, evolvesToIds: null },
    { _id: 144, name: "Articuno", types: ["Ice", "Flying"], evolvesFromId: null, evolvesToIds: null },
    { _id: 145, name: "Zapdos", types: ["Electric", "Flying"], evolvesFromId: null, evolvesToIds: null },
    { _id: 146, name: "Moltres", types: ["Fire", "Flying"], evolvesFromId: null, evolvesToIds: null },
    { _id: 147, name: "Dratini", types: ["Dragon"], evolvesFromId: null, evolvesToIds: [148] },
    { _id: 148, name: "Dragonair", types: ["Dragon"], evolvesFromId: 147, evolvesToIds: [149] },
    { _id: 149, name: "Dragonite", types: ["Dragon", "Flying"], evolvesFromId: 148, evolvesToIds: null },
    { _id: 150, name: "Mewtwo", types: ["Psychic"], evolvesFromId: null, evolvesToIds: null },
    { _id: 151, name: "Mew", types: ["Psychic"], evolvesFromId: null, evolvesToIds: null }
];
db.Pokemon.insertMany(pokemons);
