db = db.getSiblingDB('pokedex');

db.createUser({
    user: 'pokedexApp',
    pwd: 'app123!',
    roles: [
        { role: 'readWrite', db: 'pokedex' }
    ]
});

db.createCollection('Pokemon');
db.createCollection('Types');

/**********************************/
/*********** SEEDING **************/
/**********************************/

const types = [
    { name: 'Normal', weaknesses: [], strengths: [], color: '#A8A878' },
    { name: 'Fire', weaknesses: ['Water', 'Rock', 'Ground'], strengths: ['Grass', 'Bug', 'Ice', 'Steel'], color: '#F08030' },
    { name: 'Water', weaknesses: ['Electric', 'Grass'], strengths: ['Fire', 'Ground', 'Rock'], color: '#6890F0' },
    { name: 'Grass', weaknesses: ['Fire', 'Ice', 'Poison', 'Flying', 'Bug'], strengths: ['Water', 'Ground', 'Rock'], color: '#78C850' },
    { name: 'Electric', weaknesses: ['Ground'], strengths: ['Water', 'Flying'], color: '#F8D030' },
    { name: 'Ice', weaknesses: ['Fire', 'Fighting', 'Rock', 'Steel'], strengths: ['Grass', 'Ground', 'Flying', 'Dragon'], color: '#98D8D8' },
    { name: 'Fighting', weaknesses: ['Psychic', 'Flying', 'Fairy'], strengths: ['Normal', 'Ice', 'Rock', 'Dark', 'Steel'], color: '#C03028' },
    { name: 'Poison', weaknesses: ['Ground', 'Psychic'], strengths: ['Grass', 'Fairy'], color: '#A040A0' },
    { name: 'Ground', weaknesses: ['Water', 'Grass', 'Ice'], strengths: ['Fire', 'Electric', 'Poison', 'Rock', 'Steel'], color: '#E0C068' },
    { name: 'Flying', weaknesses: ['Electric', 'Ice', 'Rock'], strengths: ['Grass', 'Fighting', 'Bug'], color: '#A890F0' },
    { name: 'Psychic', weaknesses: ['Bug', 'Ghost', 'Dark'], strengths: ['Fighting', 'Poison'], color: '#F85888' },
    { name: 'Bug', weaknesses: ['Fire', 'Flying', 'Rock'], strengths: ['Grass', 'Psychic', 'Dark'], color: '#A8B820' },
    { name: 'Rock', weaknesses: ['Water', 'Grass', 'Fighting', 'Ground', 'Steel'], strengths: ['Fire', 'Ice', 'Flying', 'Bug'], color: '#B8A038' },
    { name: 'Ghost', weaknesses: ['Ghost', 'Dark'], strengths: ['Psychic', 'Ghost'], color: '#705898' },
    { name: 'Dragon', weaknesses: ['Ice', 'Dragon', 'Fairy'], strengths: ['Dragon'], color: '#7038F8' },
    { name: 'Dark', weaknesses: ['Fighting', 'Bug', 'Fairy'], strengths: ['Psychic', 'Ghost'], color: '#705848' },
    { name: 'Steel', weaknesses: ['Fire', 'Fighting', 'Ground'], strengths: ['Ice', 'Rock', 'Fairy'], color: '#B8B8D0' },
    { name: 'Fairy', weaknesses: ['Poison', 'Steel'], strengths: ['Fighting', 'Dragon', 'Dark'], color: '#F0B6BC' }
];
db.Types.insertMany(types);

const pokemons = [
    { _id: 1, name: 'Bulbasaur', types: ['Grass', 'Poison'] },
    { _id: 2, name: 'Ivysaur', types: ['Grass', 'Poison'] },
    { _id: 3, name: 'Venusaur', types: ['Grass', 'Poison'] },
    { _id: 4, name: 'Charmander', types: ['Fire'] },
    { _id: 5, name: 'Charmeleon', types: ['Fire'] },
    { _id: 6, name: 'Charizard', types: ['Fire', 'Flying'] },
    { _id: 7, name: 'Squirtle', types: ['Water'] },
    { _id: 8, name: 'Wartortle', types: ['Water'] },
    { _id: 9, name: 'Blastoise', types: ['Water'] },
    { _id: 10, name: 'Caterpie', types: ['Bug'] },
    { _id: 11, name: 'Metapod', types: ['Bug'] },
    { _id: 12, name: 'Butterfree', types: ['Bug', 'Flying'] },
    { _id: 13, name: 'Weedle', types: ['Bug', 'Poison'] },
    { _id: 14, name: 'Kakuna', types: ['Bug', 'Poison'] },
    { _id: 15, name: 'Beedrill', types: ['Bug', 'Poison'] },
    { _id: 16, name: 'Pidgey', types: ['Normal', 'Flying'] },
    { _id: 17, name: 'Pidgeotto', types: ['Normal', 'Flying'] },
    { _id: 18, name: 'Pidgeot', types: ['Normal', 'Flying'] },
    { _id: 19, name: 'Rattata', types: ['Normal'] },
    { _id: 20, name: 'Raticate', types: ['Normal'] },
    { _id: 21, name: 'Spearow', types: ['Normal', 'Flying'] },
    { _id: 22, name: 'Fearow', types: ['Normal', 'Flying'] },
    { _id: 23, name: 'Ekans', types: ['Poison'] },
    { _id: 24, name: 'Arbok', types: ['Poison'] },
    { _id: 25, name: 'Pikachu', types: ['Electric'] },
    { _id: 26, name: 'Raichu', types: ['Electric'] },
    { _id: 27, name: 'Sandshrew', types: ['Ground'] },
    { _id: 28, name: 'Sandslash', types: ['Ground'] },
    { _id: 29, name: 'Nidoran♀', types: ['Poison'] },
    { _id: 30, name: 'Nidorina', types: ['Poison'] },
    { _id: 31, name: 'Nidoqueen', types: ['Poison', 'Ground'] },
    { _id: 32, name: 'Nidoran♂', types: ['Poison'] },
    { _id: 33, name: 'Nidorino', types: ['Poison'] },
    { _id: 34, name: 'Nidoking', types: ['Poison', 'Ground'] },
    { _id: 35, name: 'Clefairy', types: ['Fairy'] },
    { _id: 36, name: 'Clefable', types: ['Fairy'] },
    { _id: 37, name: 'Vulpix', types: ['Fire'] },
    { _id: 38, name: 'Ninetales', types: ['Fire'] },
    { _id: 39, name: 'Jigglypuff', types: ['Normal', 'Fairy'] },
    { _id: 40, name: 'Wigglytuff', types: ['Normal', 'Fairy'] },
    { _id: 41, name: 'Zubat', types: ['Poison', 'Flying'] },
    { _id: 42, name: 'Golbat', types: ['Poison', 'Flying'] },
    { _id: 43, name: 'Oddish', types: ['Grass', 'Poison'] },
    { _id: 44, name: 'Gloom', types: ['Grass', 'Poison'] },
    { _id: 45, name: 'Vileplume', types: ['Grass', 'Poison'] },
    { _id: 46, name: 'Paras', types: ['Bug', 'Grass'] },
    { _id: 47, name: 'Parasect', types: ['Bug', 'Grass'] },
    { _id: 48, name: 'Venonat', types: ['Bug', 'Poison'] },
    { _id: 49, name: 'Venomoth', types: ['Bug', 'Poison'] },
    { _id: 50, name: 'Diglett', types: ['Ground'] },
    { _id: 51, name: 'Dugtrio', types: ['Ground'] },
    { _id: 52, name: 'Meowth', types: ['Normal'] },
    { _id: 53, name: 'Persian', types: ['Normal'] },
    { _id: 54, name: 'Psyduck', types: ['Water'] },
    { _id: 55, name: 'Golduck', types: ['Water'] },
    { _id: 56, name: 'Mankey', types: ['Fighting'] },
    { _id: 57, name: 'Primeape', types: ['Fighting'] },
    { _id: 58, name: 'Growlithe', types: ['Fire'] },
    { _id: 59, name: 'Arcanine', types: ['Fire'] },
    { _id: 60, name: 'Poliwag', types: ['Water'] },
    { _id: 61, name: 'Poliwhirl', types: ['Water'] },
    { _id: 62, name: 'Poliwrath', types: ['Water', 'Fighting'] },
    { _id: 63, name: 'Abra', types: ['Psychic'] },
    { _id: 64, name: 'Kadabra', types: ['Psychic'] },
    { _id: 65, name: 'Alakazam', types: ['Psychic'] },
    { _id: 66, name: 'Machop', types: ['Fighting'] },
    { _id: 67, name: 'Machoke', types: ['Fighting'] },
    { _id: 68, name: 'Machamp', types: ['Fighting'] },
    { _id: 69, name: 'Bellsprout', types: ['Grass', 'Poison'] },
    { _id: 70, name: 'Weepinbell', types: ['Grass', 'Poison'] },
    { _id: 71, name: 'Victreebel', types: ['Grass', 'Poison'] },
    { _id: 72, name: 'Tentacool', types: ['Water', 'Poison'] },
    { _id: 73, name: 'Tentacruel', types: ['Water', 'Poison'] },
    { _id: 74, name: 'Geodude', types: ['Rock', 'Ground'] },
    { _id: 75, name: 'Graveler', types: ['Rock', 'Ground'] },
    { _id: 76, name: 'Golem', types: ['Rock', 'Ground'] },
    { _id: 77, name: 'Ponyta', types: ['Fire'] },
    { _id: 78, name: 'Rapidash', types: ['Fire'] },
    { _id: 79, name: 'Slowpoke', types: ['Water', 'Psychic'] },
    { _id: 80, name: 'Slowbro', types: ['Water', 'Psychic'] },
    { _id: 81, name: 'Magnemite', types: ['Electric', 'Steel'] },
    { _id: 82, name: 'Magneton', types: ['Electric', 'Steel'] },
    { _id: 83, name: 'Farfetch’d', types: ['Normal', 'Flying'] },
    { _id: 84, name: 'Doduo', types: ['Normal', 'Flying'] },
    { _id: 85, name: 'Dodrio', types: ['Normal', 'Flying'] },
    { _id: 86, name: 'Seel', types: ['Water'] },
    { _id: 87, name: 'Dewgong', types: ['Water', 'Ice'] },
    { _id: 88, name: 'Grimer', types: ['Poison'] },
    { _id: 89, name: 'Muk', types: ['Poison'] },
    { _id: 90, name: 'Shellder', types: ['Water'] },
    { _id: 91, name: 'Cloyster', types: ['Water', 'Ice'] },
    { _id: 92, name: 'Gastly', types: ['Ghost', 'Poison'] },
    { _id: 93, name: 'Haunter', types: ['Ghost', 'Poison'] },
    { _id: 94, name: 'Gengar', types: ['Ghost', 'Poison'] },
    { _id: 95, name: 'Onix', types: ['Rock', 'Ground'] },
    { _id: 96, name: 'Drowzee', types: ['Psychic'] },
    { _id: 97, name: 'Hypno', types: ['Psychic'] },
    { _id: 98, name: 'Krabby', types: ['Water'] },
    { _id: 99, name: 'Kingler', types: ['Water'] },
    { _id: 100, name: 'Voltorb', types: ['Electric'] },
    { _id: 101, name: 'Electrode', types: ['Electric'] },
    { _id: 102, name: 'Exeggcute', types: ['Grass', 'Psychic'] },
    { _id: 103, name: 'Exeggutor', types: ['Grass', 'Psychic'] },
    { _id: 104, name: 'Cubone', types: ['Ground'] },
    { _id: 105, name: 'Marowak', types: ['Ground'] },
    { _id: 106, name: 'Hitmonlee', types: ['Fighting'] },
    { _id: 107, name: 'Hitmonchan', types: ['Fighting'] },
    { _id: 108, name: 'Lickitung', types: ['Normal'] },
    { _id: 109, name: 'Koffing', types: ['Poison'] },
    { _id: 110, name: 'Weezing', types: ['Poison'] },
    { _id: 111, name: 'Rhyhorn', types: ['Ground', 'Rock'] },
    { _id: 112, name: 'Rhydon', types: ['Ground', 'Rock'] },
    { _id: 113, name: 'Chansey', types: ['Normal'] },
    { _id: 114, name: 'Tangela', types: ['Grass'] },
    { _id: 115, name: 'Kangaskhan', types: ['Normal'] },
    { _id: 116, name: 'Horsea', types: ['Water'] },
    { _id: 117, name: 'Seadra', types: ['Water'] },
    { _id: 118, name: 'Goldeen', types: ['Water'] },
    { _id: 119, name: 'Seaking', types: ['Water'] },
    { _id: 120, name: 'Staryu', types: ['Water'] },
    { _id: 121, name: 'Starmie', types: ['Water', 'Psychic'] },
    { _id: 122, name: 'Mr. Mime', types: ['Psychic', 'Fairy'] },
    { _id: 123, name: 'Scyther', types: ['Bug', 'Flying'] },
    { _id: 124, name: 'Jynx', types: ['Ice', 'Psychic'] },
    { _id: 125, name: 'Electabuzz', types: ['Electric'] },
    { _id: 126, name: 'Magmar', types: ['Fire'] },
    { _id: 127, name: 'Pinsir', types: ['Bug'] },
    { _id: 128, name: 'Tauros', types: ['Normal'] },
    { _id: 129, name: 'Magikarp', types: ['Water'] },
    { _id: 130, name: 'Gyarados', types: ['Water', 'Flying'] },
    { _id: 131, name: 'Lapras', types: ['Water', 'Ice'] },
    { _id: 132, name: 'Ditto', types: ['Normal'] },
    { _id: 133, name: 'Eevee', types: ['Normal'] },
    { _id: 134, name: 'Vaporeon', types: ['Water'] },
    { _id: 135, name: 'Jolteon', types: ['Electric'] },
    { _id: 136, name: 'Flareon', types: ['Fire'] },
    { _id: 137, name: 'Porygon', types: ['Normal'] },
    { _id: 138, name: 'Omanyte', types: ['Rock', 'Water'] },
    { _id: 139, name: 'Omastar', types: ['Rock', 'Water'] },
    { _id: 140, name: 'Kabuto', types: ['Rock', 'Water'] },
    { _id: 141, name: 'Kabutops', types: ['Rock', 'Water'] },
    { _id: 142, name: 'Aerodactyl', types: ['Rock', 'Flying'] },
    { _id: 143, name: 'Snorlax', types: ['Normal'] },
    { _id: 144, name: 'Articuno', types: ['Ice', 'Flying'] },
    { _id: 145, name: 'Zapdos', types: ['Electric', 'Flying'] },
    { _id: 146, name: 'Moltres', types: ['Fire', 'Flying'] },
    { _id: 147, name: 'Dratini', types: ['Dragon'] },
    { _id: 148, name: 'Dragonair', types: ['Dragon'] },
    { _id: 149, name: 'Dragonite', types: ['Dragon', 'Flying'] },
    { _id: 150, name: 'Mewtwo', types: ['Psychic'] },
    { _id: 151, name: 'Mew', types: ['Psychic'] }
];
db.Pokemon.insertMany(pokemons);
